export const STRINGS = {
  app: {
    name: 'THE BLOCK',
    tagline: 'Powered by OPENLANE',
    avatarInitials: 'TB',
    avatarAriaLabel: 'Account',
  },
  search: {
    label: 'Search make, model, VIN',
    placeholder: 'Search make, model, VIN…',
    clearAriaLabel: 'Clear search',
  },
  filters: {
    heading: 'Filters',
    clearAll: 'Clear all',
    clear: 'Clear',
    openAriaLabel: 'Open filters and sort',
    noResults: 'No vehicles found',
    noResultsHint: 'Try adjusting your filters or search query',
    clearFilters: 'Clear all filters',
    showMore: (n: number) => `Show ${n} more`,
    showLess: 'Show less',
  },
  sort: {
    heading: 'Sort By',
    options: {
      auction_start:    'Ending Soon',
      current_bid_asc:  'Bid: Low → High',
      current_bid_desc: 'Bid: High → Low',
      odometer_asc:     'Lowest Mileage',
      year_desc:        'Newest Year',
      condition_desc:   'Best Condition',
    } as const,
  },
  filterLabels: {
    make:        'Make',
    bodyStyle:   'Body Style',
    fuelType:    'Fuel Type',
    titleStatus: 'Title Status',
    province:    'Province',
    price:       'Price',
    year:        'Year',
  },
  fuelOptions: ['Gasoline', 'Diesel', 'Hybrid', 'Electric'] as const,
  titleOptions: ['Clean', 'Rebuilt', 'Salvage'] as const,
  bodyOptions:  ['SUV', 'Sedan', 'Truck', 'Coupe', 'Hatchback'] as const,
  chips: {
    make:       (v: string) => `Make: ${v}`,
    body:       (v: string) => `Body: ${v}`,
    fuel:       (v: string) => `Fuel: ${v}`,
    title:      (v: string) => `Title: ${v}`,
    province:   (v: string) => `Province: ${v}`,
    priceRange: (mn: string, mx: string) => `Price: ${mn}–${mx}`,
    priceMin:   (mn: string) => `Price: ${mn}+`,
    priceUpTo:  (mx: string) => `Price: Up to ${mx}`,
    yearRange:  (yn: number, yx: number) => `Year: ${yn}–${yx}`,
    yearMin:    (yn: number) => `Year: ${yn}+`,
    yearUpTo:   (yx: number) => `Year: Up to ${yx}`,
    sort:       (label: string) => `Sort: ${label}`,
    removeAriaLabel: (label: string) => `Remove ${label}`,
  },
  vehicle: {
    currentBid:  'CURRENT BID',
    startingAt:  'STARTING AT',
    buyNow:      (price: string) => `Buy Now ${price}`,
    bids:        (n: number) => `${n} ${n === 1 ? 'bid' : 'bids'}`,
    ended:       'Ended',
    condition:   (grade: number) => `${grade.toFixed(1)} / 5.0 condition`,
  },
  pagination: {
    previous: 'Previous page',
    next:     'Next page',
    pageOf:   (current: number, total: number) => `Page ${current} of ${total}`,
  },
  range: {
    minCurrency: 'Min ($)',
    maxCurrency: 'Max ($)',
    min:         'Min',
    max:         'Max',
    clear:       'Clear',
    pricePlaceholder: { min: '$0', max: 'Any' },
    yearPlaceholder:  { min: '2000', max: '2025' },
  },
  ui: {
    scrollToTop: 'Scroll to top',
  },
  inventory: {
    allLoaded:   'All vehicles loaded',
    loadingMore: 'Loading more…',
  },
  detail: {
    comingSoon: 'Vehicle detail coming soon',
  },
} as const;
