export const STRINGS = {
  app: {
    name: 'THE BLOCK',
    tagline: 'Powered by OPENLANE',
    avatarInitials: 'TB',
    avatarAriaLabel: 'Account',
  },
  search: {
    label: 'Search make, model, VIN',
    placeholder: 'Search make, model, VIN…',
    clearAriaLabel: 'Clear search',
  },
  filters: {
    heading: 'Filters',
    clearAll: 'Clear all',
    clear: 'Clear',
    openAriaLabel: 'Open filters and sort',
    noResults: 'No vehicles found',
    noResultsHint: 'Try adjusting your filters or search query',
    clearFilters: 'Clear all filters',
    showMore: (n: number) => `Show ${n} more`,
    showLess: 'Show less',
  },
  sort: {
    heading: 'Sort By',
    options: {
      auction_start:    'Ending Soon',
      current_bid_asc:  'Bid: Low → High',
      current_bid_desc: 'Bid: High → Low',
      odometer_asc:     'Lowest Mileage',
      year_desc:        'Newest Year',
      condition_desc:   'Best Condition',
    } as const,
  },
  filterLabels: {
    make:        'Make',
    bodyStyle:   'Body Style',
    fuelType:    'Fuel Type',
    titleStatus: 'Title Status',
    province:    'Province',
    price:       'Price',
    year:        'Year',
  },
  fuelOptions: ['Gasoline', 'Diesel', 'Hybrid', 'Electric'] as const,
  titleOptions: ['Clean', 'Rebuilt', 'Salvage'] as const,
  bodyOptions:  ['SUV', 'Sedan', 'Truck', 'Coupe', 'Hatchback'] as const,
  chips: {
    make:       (v: string) => `Make: ${v}`,
    body:       (v: string) => `Body: ${v}`,
    fuel:       (v: string) => `Fuel: ${v}`,
    title:      (v: string) => `Title: ${v}`,
    province:   (v: string) => `Province: ${v}`,
    priceRange: (mn: string, mx: string) => `Price: ${mn}–${mx}`,
    priceMin:   (mn: string) => `Price: ${mn}+`,
    priceUpTo:  (mx: string) => `Price: Up to ${mx}`,
    yearRange:  (yn: number, yx: number) => `Year: ${yn}–${yx}`,
    yearMin:    (yn: number) => `Year: ${yn}+`,
    yearUpTo:   (yx: number) => `Year: Up to ${yx}`,
    sort:       (label: string) => `Sort: ${label}`,
    removeAriaLabel: (label: string) => `Remove ${label}`,
  },
  vehicle: {
    currentBid:  'CURRENT BID',
    startingAt:  'STARTING AT',
    buyNow:      (price: string) => `Buy Now ${price}`,
    bids:        (n: number) => `${n} ${n === 1 ? 'bid' : 'bids'}`,
    ended:       'Ended',
    condition:   (grade: number) => `${grade.toFixed(1)} / 5.0 condition`,
    lot:         'Lot',
  },
  pagination: {
    previous: 'Previous page',
    next:     'Next page',
    pageOf:   (current: number, total: number) => `Page ${current} of ${total}`,
  },
  range: {
    minCurrency: 'Min ($)',
    maxCurrency: 'Max ($)',
    min:         'Min',
    max:         'Max',
    clear:       'Clear',
    pricePlaceholder: { min: '$0', max: 'Any' },
    yearPlaceholder:  { min: '2000', max: '2025' },
  },
  ui: {
    scrollToTop: 'Scroll to top',
  },
  inventory: {
    allLoaded:   'All vehicles loaded',
    loadingMore: 'Loading more…',
  },
  bidding: {
    placeBid:             'Place Bid',
    raiseBid:             'Raise Bid',
    reviewBid:            'Review Bid',
    confirmBid:           'Confirm Bid',
    back:                 'Back',
    continueBrowsing:     'Continue Browsing',
    currentBid:           'Current Bid',
    yourBid:              'Your Bid',
    minimumBid:           'Minimum bid',
    reserveHidden:        'Hidden',
    reserve:              'Reserve',
    winning:              'Winning',
    won:                  'WON',
    bidPlaced:            'Bid Placed',
    youBoughtIt:          'You Bought It!',
    currentlyWinning:     "You're currently winning",
    boughtIt:             "You've purchased this vehicle",
    confirmTerms:         'By placing this bid you agree to the auction terms.',
    errorTooLow:          (min: string) => `Bid must be at least ${min}`,
    errorExceedsBuyNow:   'Bid cannot exceed the Buy Now price',
    errorInvalid:         'Please enter a valid bid amount',
    incrementLabel:       (amount: string) => `+${amount}`,
    wonHeading:           'You won this vehicle',
    wonSubtext:           'This vehicle has been purchased and removed from active inventory.',
    amountPaid:           'Amount Paid',
    purchasedViaBuyNow:   'Purchased via Buy Now',
    purchasedViaAuction:  'Won via auction bid',
    buyNowPrice:          'Buy Now Price',
    confirmBuyNow:        'Confirm Purchase',
    cancel:               'Cancel',
    lotLabel:             'Lot',
  },
  nav: {
    bids:         'My Bids',
    won:          'Won',
    liked:        'Liked',
    clearView:    'Back to all inventory',
    allInventory: 'All Inventory',
  },
  empty: {
    noResults:     'No vehicles found',
    noResultsHint: 'Try adjusting your filters or search query',
    bids:          'No active bids',
    bidsHint:      'Place a bid on any vehicle to track it here',
    won:           'No vehicles won yet',
    wonHint:       'Win an auction or use Buy Now to see vehicles here',
    liked:         'No liked vehicles',
    likedHint:     'Heart vehicles you want to keep an eye on',
  },
  likes: {
    like:   'Like this vehicle',
    unlike: 'Unlike this vehicle',
  },
  drawer: {
    viewDetails:     'View details',
    close:           'Close vehicle details',
    specifications:  'Specifications',
    condition:       'Condition',
    damageNotes:     'Damage Notes',
    dealership:      'Selling Dealership',
    placeBid:        'Place Bid',
    buyNowAvailable: 'Buy Now Available',
  },
  specs: {
    year:         'Year',
    make:         'Make',
    model:        'Model',
    trim:         'Trim',
    engine:       'Engine',
    transmission: 'Transmission',
    drivetrain:   'Drivetrain',
    fuelType:     'Fuel Type',
    odometer:     'Odometer',
    bodyStyle:    'Body Style',
    extColor:     'Exterior Color',
    intColor:     'Interior Color',
  },
  detail: {
    comingSoon: 'Vehicle detail coming soon',
  },
} as const;
